spring.application.name=backend
spring.application.name=backend

# Conexão com o banco indutime que você acabou de criar
spring.datasource.url=jdbc:postgresql://localhost:5432/indutime
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI

# Esta linha faz o Spring criar e atualizar as tabelas sozinho!
spring.jpa.hibernate.ddl-auto=update

# Exibe no terminal as tabelas sendo criadas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true